### ISSUE TITLE
Error in code for replacing escaped characters

### ISSUE THREAD

**Issue by ha-ina** [rocketbob/gdl90_2_g496#1]
In the code escaped characters are  properly replaced correctly, but then overwritten again by the old content.
The corrected version should be like this:
   int m = 0;
    for (int i = 0; i < len; i++) { // Unpack buffer.  Remove extra bytes.
      if (packetBuffer[i] == 0x7D) { // escape control character
        i++;  // look at next character
        if (packetBuffer[i] == 0x5E) { // this is 0x7E ^ 0x20, which is an escaped 0x7E
          messageBuffer[m] = 0x7E;
          Serial.print("Replaced ");Serial.print(packetBuffer[i],HEX);Serial.print(" with ");Serial.println(messageBuffer[m],HEX);
        } else if (packetBuffer[i] == 0x5D) { // this is 0x7D ^ 0x20, which is an escaped 0x7D
          messageBuffer[m] = 0x7D;
          Serial.print("Replaced ");Serial.print(packetBuffer[i],HEX);Serial.print(" with ");Serial.println(messageBuffer[m],HEX);
        }
      } **else** { // all OTHER characters
        messageBuffer[m] = packetBuffer[i]; // copy unescaped characters
      }
      m++;
    }
    len = m; // this is the new length of the message with escape symbols (0x7D) removed

**Comment by rocketbob** [comment]
Thanks for the changes.  I've merged them in the master branch and will do some testing.
